checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    external_code_coverage:
        timeout: 720
    pylint:
        python_version: 3
        config_file: '.pylintrc'

